### PR TITLE
Bump VS2022 versions for new release

### PR DESCRIPTION
**Pull request by mjcarroll**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I followed @wolfv's lead from #51 to add the new versions

### CODE REVIEW

**Comment by mjcarroll** [comment]
@conda-forge-admin, please rerender

**Comment by mjcarroll** [comment]
Perhaps I am missing something here, but it seems that the rendered feedstocks aren't iterated in the same order?

**Comment by mjcarroll** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Is there something specific in 17.5 that you need? I was thinking about doing the same thing, but since 17.6 is around the corner, I think it would make sense to wait. In particular, building every major.minor here is probably overkill.

**Comment by mjcarroll** [comment]
> Is there something specific in 17.5 that you need? I was thinking about doing the same thing, but since 17.6 is around the corner, I think it would make sense to wait. In particular, building every major.minor here is probably overkill.

The tools version bumped so the vcvars script no longer works, as far as I can tell.  I agree that tracking every release is probably too much churn, so if there is another mechansim to keep these in sync, that would be welcome.

**Comment by mjcarroll** [comment]
> What problems are you encountering & where?

It happens when activating a workspace, in the `vs2022_compiler_vars.bat` file.

```
C:\Program Files\Microsoft Visual Studio\2022\Community>CALL "VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.34
```

Returns:

```
Toolset directory for version '14.34' was not found
```

Manually editing the script and increasing this to 14.35 (to match my installed toolset) seems to resolve the issue.

**Comment by h-vetinari** [comment]
Ah, you're running this against a local MSVC compiler? Yeah, then I'm not surprised that you're stumbling over a version mismatch... Still, you have the opportunity to install specific major versions on your own machine, this feedstock is much more constrained (IMO) by what the needs of our CI are, local usage is pretty niche I believe.

Ultimately it's up to @conda-forge/vc to chime in resp. decide on this, but I'd wait for 17.6

**Comment by h-vetinari** [comment]
> I think the future proof way would be to check the error code and if `%CONDA_BUILD%` is not set retry without `vcvars_ver`.

I gave this a shot in #56

**Comment by h-vetinari** [comment]
> I gave this a shot in https://github.com/conda-forge/vc-feedstock/pull/56

@mjcarroll, ideally the new builds should now also work with your local 17.5, without needing this PR anymore. :)

**Comment by mjcarroll** [comment]
Thanks!

**Pull request closed without merging**
