### PR TITLE
Win arm64

### PR DESCRIPTION
**Pull request by isuruf**
We are getting rid of some hacks we had for other platforms

- ucrt is not used as win-arm64 is supported only for windows>=10 and ucrt DLLs are in the system and the ones in the
  system always takes precedence
- `vs2015_runtime` is renamed to `vc14_runtime` and `vs2015_runtime` is kept for compatibility in x86
- added a new `vs_win-64=2022` output

### CODE REVIEW

**Comment by isuruf** [comment]
cc @conda-forge/core, @conda-forge/staged-recipes, @chenghlee

**Review by xhochy — APPROVED** [review]
Looking good!

**Review by chenghlee — APPROVED** [review]
`vs*_runtime` -> `vc*_runtime` naming change (along with the other bits) make sense to me. I'll open a ticket to make sure similar changes are made to Anaconda's `main` channel.

**Comment by isuruf** [comment]
Thanks.

**Comment by h-vetinari** [comment]
Getting a bunch of clobber warnings, I suspect related to this PR:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::vc14_runtime-14.34.31931-h5081d32_13, conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_11
  path: 'library/bin/concrt140.dll'

ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::vc14_runtime-14.34.31931-h5081d32_13, conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_11
  path: 'library/bin/msvcp140.dll'

[and so on]
```

**Comment by h-vetinari** [comment]
Interestingly, it also appears to clobber the package artefacts itself, which would seem to imply that the required libs aren't there anymore when the "environment snapshot" after building is taken, and so conda thinks those libs belong to whatever artefact is being packaged:
```
ClobberWarning: Conda was asked to clobber an existing path.
  source path: C:\Miniforge\pkgs\vs2015_runtime-14.34.31931-h4c5c07a_11\Library\bin\concrt140.dll
  target path: D:\bld\boost-split_1683161338849\_test_env\Library\bin\concrt140.dll
```

**Comment by h-vetinari** [comment]
I also see this showing up in the CI on PRs that were merged to main, e.g. [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=700514&view=results), meaning that this will percolate to windows builds very quickly.

**Comment by h-vetinari** [comment]
Good news: I think we're not actually repackaging the windows-libs in regular artefacts, which takes off a lot of the pressure.

It seems I misread the way the clobberwarnings are emitted (in two parts). 

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::vc14_runtime-14.34.31931-h5081d32_13, conda-forge/win-64::vs2015_runtime-14.34.31931-h4c5c07a_11
  path: 'library/bin/concrt140.dll'

[...]

ClobberWarning: Conda was asked to clobber an existing path.
  source path: C:\Miniforge\pkgs\vs2015_runtime-14.34.31931-h4c5c07a_11\Library\bin\concrt140.dll
  target path: D:\bld\boost-split_1683161338849\_test_env\Library\bin\concrt140.dll  # this one will be adapted to whatever feedstock we're in
```

**Comment by h-vetinari** [comment]
Ah, Isuru has a [fix](https://github.com/conda-forge/vc-feedstock/pull/59), thanks for the super quick response!

**Pull request merged**
