### PR TITLE
ENH rerender for proper version

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

It appears that the version reported by cl.exe is different from what is in the recipe. This PR fixes that.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
OK. The version number before was right, but now the recipe is correct too.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by csosborn** [comment]
Hi @beckermr. This and the previous PR (#11) have been causing the `vc` package to update in situ without a version change, breaking a dependent package build in ways that my team is struggling to understand. Could you help me understand what is changing here, and why it doesn't indicate a version change as well? Also, do you know if there is a way to lock in the previous vc build number (or something similar) to get back to the previous package (we're getting `vc` implicitly through the `compiler('cxx')` directive in the affected recipe). Thanks!

**Comment by beckermr** [comment]
Which build? We are upgrading the windows compilers and so are pushing new versions.

**Comment by csosborn** [comment]
Unfortunately it's a closed source project that I can't link to, but the failure that suddenly started appearing suggests an incompatibility between the compiler used within the `conda build` run and that used to compile a library (in this case `spdlog`) the build depends on. That and several other library dependencies are provided by Conan, not Conda, and that may be part of the problem. Does conda-build assume that all build inputs are provided by conda, and thus that everything uses the same compiler implicitly?

**Comment by beckermr** [comment]
this depends on the channels you use. without seeing more info, we cannot be of help here. verry sorry! if you can share some info we might be able to help diagnose.

**Pull request merged**
