### PR TITLE
Fix for VS2019 with vc141 toolchain

### LINKED ISSUE #41: Fix CMAKE_GENERATOR when Visual Studio 2019 is used for vc141
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

cc @henryiii

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #41

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by wshanks** [comment]
@isuruf When should the fix here be available from the conda-forge repo? I still see [the problem with new builds](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=437796&view=logs&j=4df4d378-e321-55ba-2201-2fae9d1dab78&t=c6f47b81-e655-562b-3dd0-a092d624d1cf&l=449) now. Does the build number in the recipe need to be bumped?

**Comment by isuruf** [comment]
Original issue should be fixed now. I think the issue in llvmlite is that llvmdev package was built with the 2017 image and the DIA SDK path was hardcoded in the llvmdev package, but the location changed in 2019 image.

**Comment by jakirkham** [comment]
Currently `llvmlite` uses `llvmdev` version `11.1`. So does this just come down to rebuilding that one?

**Pull request merged**
