### PR TITLE
MSVC 14.38

### LINKED ISSUE #69: New DLLs to copy for VS>=19.38; need to expand tests.
When we activated VS2022, I [double-checked](https://github.com/conda-forge/vc-feedstock/pull/46#issuecomment-1288555617) if there were no new satellite libraries to the vcruntime.

Based on a recent [blogpost](https://devblogs.microsoft.com/cppblog/c11-threads-in-visual-studio-2022-version-17-8-preview-2/) about C11 threading support in Visual Studio, it appears that there will be two new DLLs (`vcruntime140_threads.dll` / `vcruntime140_threadsd.dll`) as of VS 17.8 that we'll have to include.

Or rather, they should get included by the repack mechanism and we'll just have to add tests for it, compare:
https://github.com/conda-forge/vc-feedstock/blob/5cbd681a12658623d1c661dfe7b40a148d94d5eb/recipe/meta.yaml#L125-L135

where we could add something like:
```yaml
        {% if vsyear == "2022" %}
        - if not exist %LIBRARY_BIN%\vcruntime140_threads.dll exit 1
        - if not exist %LIBRARY_BIN%\vcruntime140_threadsd.dll exit 1
        {% endif %}
```

### PR DESCRIPTION
**Pull request by h-vetinari**
Microsoft recently [released](https://devblogs.microsoft.com/cppblog/whats-new-for-cpp-developers-in-visual-studio-2022-17-8/) VS 17.8, which will presumably make it into the default images soon (and would break the vs2022 compilers then, see #67).

I tried to update a while ago, but had to chase down a conda-smithy bug (could not rerender recipe anymore for some reason...).

Closes #69

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/vc, this is ready, PTAL :)

**Comment by h-vetinari** [comment]
Gentle ping @conda-forge/vc

**Comment by isuruf** [comment]
I was going to ask you to check that the azure and gha images have been updated. Otherwise this would break builds. Please stop merging in feed stocks that you are not a maintainer of without asking for a review from core. This is an abuse of power. This has happened multiple times. I will bring it up next meeting.

**Comment by isuruf** [comment]
Cc @conda-forge/core

**Comment by h-vetinari** [comment]
> Please stop merging in feed stocks that you are not a maintainer of without asking for a review from core. This is an abuse of power.

You know that I've been involved on this feedstock for quite a while and I consider myself a maintainer here, whether I'm in meta.yaml or not. I'd appreciate if you could avoid throwing around words like "abuse", because if this is abuse, I'm handing in my keys voluntarily.

**Comment by isuruf** [comment]
Yes, I do consider it abuse. I really really appreciate your work in conda-forge, but the way you go about it by pushing everyone's buttons is wrong. Please follow the processes in place. If you can't, please do.

**Comment by h-vetinari** [comment]
So if I add myself to the `meta.yaml` here (which would be justified based on previous involvement here and in our compiler stack generally), it magically would stop being abuse?

> Please follow the processes in place

The guideline was "wait for a response for two weeks", which I did.

**Comment by isuruf** [comment]
> So if I add myself to the meta.yaml here (which would be justified based on previous involvement here and in our compiler stack generally), it magically would stop being abuse?

After the interaction here I wouldn't accept such a PR anyway.

> The guideline was "wait for a response for two weeks", which I did.

No, the guideline is to wait for a week or two and ask someone else from core to merge.

**Pull request merged**
